index.js
lib/module/moment.js
lib/timeline/Graph2d.js
lib/timeline/Timeline.js
lib/timeline/component/GraphGroup.js
lib/timeline/component/Legend.js
lib/timeline/component/LineGraph.js
lib/timeline/component/graph2d_types/bar.js
lib/timeline/component/graph2d_types/line.js
lib/timeline/component/graph2d_types/points.js
rollup.config.js

@yotamberk Here are the changes we talked about...With this changes the build works and the examples are functional.
@yotamberk You can ignore the patch I send you via email and just use this pull-request.

fix: fixed rollup build

---

lib/timeline/Range.js

fixes #26 via https://github.com/yotamberk/timeline-plus/issues/60

fix: firefox scroll issue

---

examples/graph2d/13_localization.html
examples/timeline/groups/nestedGroups.html
examples/timeline/items/visibleFrameTemplateContent.html
examples/timeline/other/localization.html
examples/timeline/other/requirejs/requirejs_example.html
examples/timeline/other/requirejs/scripts/main.js
examples/timeline/styling/itemTemplates.html
examples/timeline/styling/weekStyling.html

fixed some problems in the examples

chore(examples): fixed some problems in the examples

---

.babelrc
package.json

fix(babel): add CSS support

---

.circleci/config.yml
.commitlintrc.js
.gitignore
.releaserc.yml
package-lock.json
package.json

Builds, tests (with coverage) and publishes if everything passes on master branch. Linting is commented out at the moment as there are 21 jsdoc comments missing or invalid (should be enabled when there are no linting issues in the code base).
Resolves #42 and resolves #44.

ci: set it up

---

docs/timeline/index.html

Update of docs following the History of file `OptionsPage.js` of Timeline-plus.

Update docs with new options of Timeline-plus

---

lib/timeline/component/ItemSet.js
lib/timeline/component/LineGraph.js

Fixes #97 - Using vis.DataSet _idProp instead of _fieldId

---

docs/graph2d/index.html
docs/timeline/index.html
lib/timeline/Graph2d.js
lib/timeline/Timeline.js

Closes #95 
Demo: http://jsfiddle.net/zm7sgfup/

feat(graph2d,timeline): return the id of the custom time if clicked

---

lib/timeline/component/item/Item.js

fix: removed console.log introduced by #69

---

docs/timeline/index.html
lib/timeline/component/ItemSet.js
lib/timeline/component/item/Item.js
lib/timeline/locales.js

Closes #78 
Demo: http://jsfiddle.net/mvckt5f2/
Screenshot:

feat(timeline): add localization option for delete button title

---

dist/types/index.d.ts
types/index.d.ts

Added/fixed types:
Items:
editable
selectable
Groups:
subgroupVisibility
Timeline:
preferZoom
sequentialSelection

Add/fix missing types to index.d.ts

---

dist/types/index.d.ts
types/index.d.ts

Added missing types for the tooltip in index.d.ts

Added missing types for the tooltip.

---

lib/timeline/component/item/RangeItem.js

Fixes #121 - Support for white-space normal in content of range items

---

HISTORY.md

I've updated HISTORY.md for the upcoming V6.0.0! I'm planning on officially publishing the version on October 21st . Hopefully by then all that is needed to be done for the publication can get done. 
Seems like an achievable task. 
Once we get this version published, I will archive `timeline-plus` once and for all~!

fix: update HISTORY.md

---

types/index.d.ts

Added selectable type in TimelineItem interface and subgroupVisibility in TimelineGroup

Fix: Added missing types in index.d.ts

---

lib/timeline/component/CurrentTime.js
lib/timeline/component/CustomTime.js
lib/timeline/component/item/Item.js

Closes #187 
Demo: http://jsfiddle.net/ostke1fm/2/

fix(timeline) custom locales do not work 

---

package-lock.json
package.json

fix: update keycharm

---

lib/timeline/component/item/BoxItem.js

fix: align on specific boxItem

---

lib/timeline/Core.js

Solves the inconsistency illustrated in #109.
fix #109

fix: add mousewheel listener to top/bottom panel

---

lib/timeline/component/item/BackgroundItem.js
lib/timeline/component/item/BoxItem.js
lib/timeline/component/item/ClusterItem.js
lib/timeline/component/item/PointItem.js
lib/timeline/component/item/RangeItem.js

fix: typescript uncaught error #161

---

lib/timeline/locales.js

fix: issue #209

---

docs/timeline/index.html
lib/timeline/Timeline.js
types/index.d.ts

I updated doc and d.ts files, just tell me if something else is needed !
It fixes #198 :)

feat(timeline): #198 - Add param to not zoom in with Timeline.focus

---

lib/timeline/component/item/BoxItem.js
lib/timeline/component/item/ClusterItem.js
lib/timeline/component/item/Item.js
lib/timeline/component/item/PointItem.js
lib/timeline/component/item/RangeItem.js

This was the real way to solve #209.
I could reproduce the issue in https://visjs.github.io/vis-timeline/examples/timeline/editing/editingItemsCallbacks.html
Solved now with this PR

fix: error in issue #209

---

lib/DOMutil.js

fix: issue 231

---

lib/shared/Configurator.js

fix: issue 181

---

lib/timeline/TimeStep.js

fix: issue #193

---

.gitignore
generate-examples-index-graph2d.json
generate-examples-index-timeline.json
package-lock.json
package.json

The new examples including config files and updated gitignore.

chore(examples): update Vis Dev Utils

---

lib/shared/Activator.js
test/Activator.test.js

fix: issue #257
Cleanup activator.current reference on deactivate.
Add test for activator.

fix: issue #257

---

docs/timeline/index.html
lib/timeline/locales.js

Polish locale

---

lib/timeline/component/item/ClusterItem.js

fix: showStipes not working (#266)

---

package.json

fix(build): set correct bundle entries (#319)

---

lib/timeline/component/DataAxis.js
lib/timeline/component/ItemSet.js
lib/timeline/component/LineGraph.js
lib/timeline/component/item/ClusterItem.js
package-lock.json
package.json
rollup.build.js
rollup.config.js

chore: update uuid version

---

lib/timeline/component/CustomTime.js

fix options.time validation in CustomTime constructor to allow 0 value

---

docs/timeline/index.html

Fix the Timeline Examples URL

---

lib/timeline/Core.js
lib/timeline/Timeline.js
lib/timeline/component/Group.js

**Thank you for contributing to vis.js!!**
fixes #453

perf: emit timeline events only when listeners exist

---

docs/timeline/index.html
lib/timeline/locales.js

Add Portuguese localization and update documentation.
Language codes:
- pt
- pt_BR
- pt_PT

Add Portuguese localization

---

CONTRIBUTING.md

Just a typo correction in the contributing page.
This is my first pull request ever.
If I made any mistake, I will appreciate your feedback.

docs: fix typo on contributing page url

---

lib/timeline/component/ClusterGenerator.js
lib/timeline/component/item/ClusterItem.js

First pull request ever...
This fixed issues on my end so might help
fix #511

fix: #511 - Update ClusterItem.js isVisible issue

---

docs/timeline/index.html
lib/timeline/locales.js

Requested from PrimeFaces ticket: https://github.com/primefaces/primefaces/issues/6932

Locales: Swedish and Norwegian

---

lib/timeline/component/item/PointItem.js

Fixes #450 
Also, adjusted the spacing between the dot and the content.

fix: positioning of PointItem's dot (#450)

---

package.json

This does nothing at the moment but it's one of the things blocking Vis Dev Utils updates (the file would disappear from the package).

chore(package): add HISTORY.md to files

---

docs/timeline/index.html

Typo in the example.
**Thank you for contributing to vis.js!!**
Please make sure to check the following requirements before creating a pull request:

Fix Grid Backgrounds example

---

lib/timeline/Range.js

Stop rolling on timeline destroy

---

package-lock.json
package.json
rollup.config.js

We don't use any node builtins and don't polyfill them in most builds anyway

chore(deps): remove rollup-plugin-node-builtins
