visjs/vis-timeline

examples/graph2d/08_performance.html, examples/graph2d/13_localization.html, examples/timeline/dataHandling/loadExternalData.html, examples/timeline/editing/tooltipOnItemChange.html, examples/timeline/groups/groups.html, examples/timeline/groups/nestedGroups.html, examples/timeline/other/functionLabelFormats.html, examples/timeline/other/loadingScreen.html, examples/timeline/other/localization.html, examples/timeline/other/onTimeout.html, examples/timeline/other/performance.html, examples/timeline/other/rtl.html, examples/timeline/other/stressPerformance.html, examples/timeline/other/verticalScroll.html, examples/timeline/styling/itemTemplates.html, examples/timeline/styling/weekStyling.html
Githup is all https causing mixed content from CDN's to fail loading with the below message. All CDN URL's used in examples should be changed to https.
Blocked loading mixed active content “http://ajax.googleapis.com/ajax/libs/jquery/1.10.1/jquery.min.js”
=> Change script CDN URL's to https

examples/graph2d/16_bothAxisTitles.html
The validator expects an object containing "dataAxis.left.title.text". Therefore title can't be undefined.
=> fixed error when hiding title in graph2d-example (fixes #50)

lib/module/hammer.js, package-lock.json, package.json
The original Hammer.js project seems unmaintained and doesn't work in node.
All 50 tests run now although 49 out of them fail.
Closes #87.
=> chore(deps): switch to @egjs/hammerjs

docs/timeline/index.html, lib/timeline/Core.js
Added capability to fire an event "dragover" when dragging over a timeline element.
Can be useful to have kind of interactive dragging (eg: display information depending on the dragging location to the user).
=> Added firing dragover event

lib/timeline/component/Group.js
[Moved PR from timeline-plus to this repository]
Range elements exceeding lower and upper boundary are not displayed. (not only when timeline is initialized, but also on zoom in/out)
I've seen some discussions about issue that could be the same than the one I fix here, except that I've not tried to go with a single loop: #157
In summary, I've found 2 issues:
same search function is used for start and end date search when trying to find a visible element in the orderedElement. In case of range (end), we only need to search with an element having an end date greater than the lower boundary. Considering a range as not visible because its end date is greater than the upper boundary is wrong.
when tracing visible items, we use a break condition that takes into account only the end date. It's …
=> Fixed display of ranges exceeding lower and upper boundaries

docs/timeline/index.html, examples/timeline/index.html, examples/timeline/markers/customTimeMarkers.html, examples/timeline/markers/customTimeMarkersEditable.html, lib/timeline/Core.js, lib/timeline/component/CustomTime.js
Closes #105 
Demo: http://jsfiddle.net/qwapcbve/
=> feat(timeline): add an option to make the custom marker editable

examples/timeline/markers/customTimeMarkersEditable.html
=> fix(examples): fix that a marker is not displayed due to an id collision

docs/timeline/index.html, lib/timeline/component/CustomTime.js
Closes #131 
This PR adds two custom events
* `markerchange`: fired when the marker title has been changed([demo](http://jsfiddle.net/cu978pq1/)).
* `markerchanged`: fired when an alteration to the marker title is committed([demo](http://jsfiddle.net/1cx8r0og/)).
=> feat(timeline): add custom events for markers

lib/timeline/.eslintrc, lib/timeline/Core.js, lib/timeline/DateUtil.js, lib/timeline/Range.js, lib/timeline/Stack.js, lib/timeline/TimeStep.js, lib/timeline/Timeline.js, lib/timeline/component/ClusterGenerator.js, lib/timeline/component/CurrentTime.js, lib/timeline/component/DataAxis.js, lib/timeline/component/DataScale.js, lib/timeline/component/Group.js, lib/timeline/component/ItemSet.js, lib/timeline/component/item/BackgroundItem.js, lib/timeline/component/item/BoxItem.js, lib/timeline/component/item/ClusterItem.js, lib/timeline/component/item/Item.js, lib/timeline/component/item/PointItem.js, lib/timeline/component/item/RangeItem.js
This PR fixes all lint errors created by js-docs missing in all files.
Note: I want to get rid of JSdoc completely. 
It is not used in our docs and TBH I find it completely useless.
I believe it was replaced by types from TS. 
I wanted to get the lint fixed for Version 6.0.0,  but in consideration that we will probably get rid of it completely in future versions - if you agree in future discussions.
=> fix: all lint errors

.circleci/config.yml
Otherwise dist is not saved and screenshots of empty canvases are taken.
Closes #143.
=> ci: add build dependency to examples

types/index.d.ts
Currently a variable of type `TimelineGroup[]` cannot be used in the constructor for `Timeline` nor the `setData` method.
`TimelineGroup.content` is of type `string | HTMLElement` which is currently not assignable to `DataGroupCollectionType.content`. However the docs say a group can contain an `HTMLElement`.
A Timeline Group's `subgroupOrder` function accepts a string or a sort function. The `TimelineGroup`'s function `(a: any, b: any) => number`  does not match the `DataGroup`'s function `() => void`. `DataGroup`'s function was changed to be a sort function like `TimelineGroup`.
Now a `TimelineGroup[]` can be used in the constructor to make a `Timeline`.
The other option would be to set `Timeline`'s constructor to TimelineGroup instead of DataGroup and all methods as well.
=> Make DataGroup compatible with TimelineGroup

lib/timeline/component/CurrentTime.js, lib/timeline/component/CustomTime.js, lib/timeline/component/item/Item.js
Extend existing locales instead of replacing them. Fix #55.
This also extends all locales to use the default locale for any
missing key. So if a new localization option is added in the future,
every locale which does not yet have the new option translated will use
the default english one.
=> feat(timeline): extend existing locales

lib/timeline/component/Group.js
**Problem:** 
This line (in Group.js)
```
stack.nostack(this.visibleItems, margin, this.subgroups, this.itemSet.options.stackSubgroups);
```
in the function `_redrawItems` uses the `this.subgroups` `top` and `height` properties to set its items `top` property.
Since `_updateSubGroupHeights` is called before `this.visibleItems` is set in `_redrawItems`, then the subgroups height and visible are 0 and false accordingly which sets the items in the 2nd+ subgroups items top property to be 0 and thus overlap all the items in the group.
**Soution:**
Call `_updateSubGroupHeights` after setting `this.visibleItems` but before `stack.nostack(...`
I took the function `_updateSubGroupHeights` out of the redraw queue and called it each time `this.visibleItems` was set in `_redrawItems`.
This seems to …
=> Resolve 156: Subgroups overlap when scrolling vertically

examples/timeline/other/localization.html, lib/timeline/Core.js, lib/timeline/Range.js, lib/timeline/TimeStep.js, lib/timeline/Timeline.js, lib/timeline/component/CurrentTime.js, lib/timeline/component/CustomTime.js, lib/timeline/component/DataAxis.js, lib/timeline/component/Group.js, lib/timeline/component/ItemSet.js, lib/timeline/component/TimeAxis.js, lib/timeline/component/item/BoxItem.js, lib/timeline/component/item/ClusterItem.js, lib/timeline/component/item/Item.js, lib/timeline/component/item/PointItem.js, lib/timeline/component/item/RangeItem.js
fixes #150
re-implement https://github.com/yotamberk/timeline-plus/pull/168
=> Reimplement performance improvements

types/index.d.ts
`TimelineTooltipOption` requires you to define a `template`, but it already has a default value in the documentation. Not specifying the `template` still works as expected when changing the type to an optional and not defining it.
=> Make 'template' optional in 'TimelineTooltipOption'

package-lock.json, package.json
Updated hammerjs to include their fix for shadow-dom support. Refer to the original visjs ticket and related hammerjs ticket for details.
=> fix: updated hammerjs to 2.0.16 to include shadom-dom fix (visjs#116)

lib/timeline/component/Group.js
Currently, the timeline always tries to stack all items inside each subgroup, including non visible items.
Solves the issue #115
=> fix(timeline): only stack visible items inside subgroups

types/index.d.ts
This updates the TypeScript definition file to add some missing options and restrict some string options to their available options.
Fixes: https://github.com/visjs/vis-timeline/issues/216
=> update typings for some missing Timeline options

lib/timeline/Core.js
This should solve #213 once and for all!
The border calculations done are really not needed... 
They were used in the past for various reasons that are irrelevant now. 
I've simplified the calculations to be constantly 1px and thus will no longer be dependent on `clientHeight` and `offsetHeight` which are very unstable in their returns due to being dependent on how the browser rounding.
=> fix: border calculations in browser zoom bugs

docs/graph2d/index.html, lib/timeline/optionsGraph2d.js
I still need to update docs, but opening this early as a pseudo issue report too.
I noticed that the week option wasn't available on Graph2D. I think I used it previously but looking through the git history I must be mistaken.
Commit 65060a0f394d720d3f51e81efcc17a8154332fcd introduced the week options for Timeline but not Graph2D. I experimented and the only thing missing is adding it into the options from the looks of it. I copied and pasted the lines across and then my Graph2D worked just like I wanted it too.
Is there anything else I'm missing?
Otherwise I need to update docs. Do I also need to provide an example?
=> Week options missing from graph2d options

examples/timeline/groups/verticalItemsHide.html
`examples/timeline/groups/verticalItemsHide.html`  has a mistake: 'a is not defined'.
=> fix: a is not defined in this example.

docs/timeline/index.html
cluster.titleTemplate documentation doesn't mention `{count}` which it will replace by the number of items in the cluster. Adding this in the documentation.
=> Add description for cluster.titleTemplate in docs

lib/DOMutil.js
`if (!navigator)` throws an error when `navigator` has never been declared before such as with Node / Next.js.
Another option is to to check `typeof navigator === 'undefined'`. I chose to do a try...catch because I also want it to return `en` for any falsy value and not just `undefined` (if `navigator` were declared, but `null` for example).
=> Catch when navigator is undefined - fixes #231

lib/timeline/component/ItemSet.js
This is to fix: https://github.com/visjs/vis-timeline/issues/202
Check if both editable options are true instead of one by one
=> fix: check if both updateGroup and updateTime are falsey - fixes #202

lib/timeline/Graph2d.js, lib/timeline/Timeline.js, lib/timeline/component/ItemSet.js, lib/timeline/component/LineGraph.js, lib/util.js, package-lock.json, package.json, test/Timeline.test.js
Switch from the deprecated type property of Data Set to Data Pipes. This solves some or maybe all issues from #254.
~PS: There is a bug in Vis Data that prevents this from working see visjs/vis-data/pull/78.~
PS: I'm not going to change this here as it's off topic but this library has no runtime dependencies. Everything's bundled by Rollup so all the dependencies listed in package.json are completely unnecessary to use this.
=> fix(type-coercion): use Data Pipes

lib/timeline/Timeline.js, lib/timeline/component/Group.js, lib/timeline/component/ItemSet.js
This is my attempt at solving #183.
There are two key differences when compared to #235:
1. This one actually works better.
2. This one doesn't blindly throw away all listeners.
Leaks in my tests (very rough measurements on my device):
- Upstream: 3 MB/s
- #235: 250 KB/s
- This: about 0 KB/s
PS: For the tests I used the JSFiddle MWE from @aphix. I just decreased delays to leak more memory in shorter amount of time.
=> fix(item-set): don't leak memory when setting groups

test/canvas-mock.js
I have no idea why these were introduced as the only thing they seem to
do is break unit tests. However my guess is that they compensated for
missing features in older versions of jsdom and since they were
implemented in jsdom itself it just malfunctions now.
=> test(jsdom): remove overrides

lib/timeline/component/DataAxis.js, lib/timeline/component/ItemSet.js, lib/timeline/component/LineGraph.js, lib/timeline/component/item/ClusterItem.js, package.json, rollup.build.js, rollup.config.js
This shouldn't be noticable from the outside at all.
=> fix(deps): switch to uuid package

lib/timeline/Stack.js
fixes #343
Modified collisionByTimes to be exclusive and not consider abutting items as colliding. See original ticket for an example.
=> fix: collisionByTimes updated to be exclusive

lib/timeline/component/item/ClusterItem.js
=> fix(#373): check for showStipes option when getting DOM sizes in ClusterItem

lib/timeline/component/ClusterGenerator.js
Title was being accessed before its init causing:
```txt
ERROR ReferenceError: Cannot access 'title' before initialization
```
=> fix: ReferenceError due to access 'title' before initialization

types/index.d.ts
https://visjs.github.io/vis-timeline/docs/timeline/#Configuration_Options
snap
When moving items on the Timeline, they will be snapped to nice dates like full hours or days, depending on the current scale.
The snap function can be replaced with a custom function, or can be set to null to disable snapping
before: null not allowed
after: null allowed
**Thank you for contributing to vis.js!!**
Please make sure to check the following requirements before creating a pull request:
=> [ts] snap not declared properly (null not allowed)

lib/timeline/component/Group.js
This PR is fixing #467 where provided jsfddle for demo and steps.
This issue is happening when:
1. there are some number of items on timeline
1. every item is occupying decent time slot
1. items are following each to other
1. zoom is set in the way to see only part of single item (saying item takes 6hrs but timeline displays only 2 hrs range)
Once above conditions are satisfied `binarySearchCustom()` function call which is using to determine `initialPosByEnd` value in  Group._updateItemsInRange() function can return inappropriate value: it can indicate position of item which is pretty far from currently displayed range.
So I have fixed `initialPosByEnd` value comparator function to find out the closest item to current range.
Build and tests are passed locally.
=> Background items are not appearing during drag to the left in some cases

types/index.d.ts
The interface `TimelineOptions` of `vis-timeline` is missing the `zoomFriction` option found in the [docs](https://visjs.github.io/vis-timeline/docs/timeline/#Configuration_Options).
=> Add zoomFriction to option interface

examples/timeline/peer-build.html
The builds have to match in order to make everything work. The version before combined legacy Vis Data with peer Vis Timeline which doesn't really work.
Closes #510.
=> docs(examples): fix peer build URLs

lib/timeline/Core.js, lib/timeline/Graph2d.js, lib/timeline/optionsGraph2d.js
Close #472 
The Timeline has the `itemSet` property  but Graph2d doesn't, so the access to `itemSet.options` causes the error. 
demo: https://jsfiddle.net/1u8e4gpc/
=> Fix "Graph2d#addCustomTime doesn't work" (#472)

lib/bundle-legacy.js, lib/entry-esnext.js, lib/entry-standalone.js
This pull request exposes ClusterItem in the timeline.items export, alongside the existing exports of BoxItem, PointItem, etc
=> chore: expose ClusterItem in timeline export

lib/timeline/component/LineGraph.js
Normally dragging a line graph (or calling setRange repeatedly to sync
the range with something external) causes only partial updates (the SVG
is moved as a whole, not modified). However, if at the same time full
updates happen the graph can become moved twice: once because the items
have been moved and the second time due to the SVG offset.
To avoid this problem update the lastStart reference
position not only when the drag ends, but also on any other full graph
rebuild.
=> fix: update lastStart on every graph update

lib/timeline/component/LineGraph.js
This is a follow-up to visjs/vis-timeline#651 (sorry, I failed to do it correctly the first time). If redraw causes a full update, the SVG position needs to be reset too because the lastStart to position propagation does not happen in this branch.
=> fix: reset SVG position on full graph update

README.md
According to [GFM 6.6 Links](https://github.github.com/gfm/#links) the format is `[text](link)`.
=> Fix markdown links in README.md

lib/timeline/component/TimeAxis.js
Found multiple instances of a timeline were sharing formats. This is due to the TimeStep.FORMAT being directly referenced by each defaultOptions created within a TimeAxis.
=> fix: format options object so its unique within a TimeAxis instance

lib/timeline/Graph2d.js, lib/timeline/Timeline.js, lib/timeline/component/ItemSet.js, lib/timeline/component/LineGraph.js
This tests that the methods and properties are implemented instead of checking the prototype. Thanks to this it is now possible to use a different DataSet or DataView without extending the Vis one. This also removes some interoperability issues of the standalone build when used toghether with other Vis family libraries.
=> feat(data): allow custom DataSet/View implementations

lib/shared/Configurator.js, lib/timeline/Timeline.js
Array.isArray works with arrays that came from other contexts like web workers, instanceof Array wouldn't consider such array to be an array even though it is perfectly valid array.
Closes #749.
=> fix: purge instanceof Array from the codebase

types/index.d.ts
In my own use case, I'm trying to attach a Vue component containing an image. Some properties are computed against `scrollHeight` of this image, and this is 0 if the element is not attached to the DOM.
So returning `outerHTML` is not the same thing as returning the element itself.
**Thank you for contributing to vis.js!!**
Please make sure to check the following requirements before creating a pull request:
=> fix: add template functions can return HTMLElement

lib/shared/Configurator.js, lib/shared/Popup.js, lib/timeline/Timeline.js, lib/timeline/component/CustomTime.js, lib/timeline/component/DataAxis.js, lib/timeline/component/Group.js, lib/timeline/component/Legend.js, lib/timeline/component/TimeAxis.js, lib/timeline/component/item/Item.js, lib/util.js, package-lock.json, package.json
I added the [xss library](https://www.npmjs.com/package/xss) to improve security.
fixes #838
=> improve xss security

package.json, rollup.build.js
As stated in https://github.com/visjs/vis-timeline/pull/840#issuecomment-748640374, XSS should be listed among other dependencies as it is needed during runtime.
=> fix(deps): add XSS among peer dependencies

lib/timeline/Graph2d.js
fixes #981
`graph2d.setItems` checked `newDataSet`(it is null!) as DataViewLike, so I fixed to replace `newDataSet` to `items`.
codepen: https://codepen.io/youku_s/pen/YzNwRzP
=> fix(graph2d): graph2d.setItems doesn't work sometimes

docs/timeline/index.html, lib/timeline/Timeline.js, lib/timeline/optionsTimeline.js, lib/util.js, types/index.d.ts
I tried different ways on how to implement this and thought about the ideas previously discussed in the issue #846.
After some fiddling around I decided to keep things quite simple here, to get this off and rolling for everyone.
The basic concept includes the following:
- keep util.xss() usages unchanged
- allow to disable xss protection completely
- allow to control xss library's behavior using its public interfaces
Note: This still means, that the current default behavior will remain unchanged, but users will be able to gain control over it and have alternative options. See below.
To achieve things I basically did the following: 
1. replaced the xss export in util.js with a dynamic getter using Object.defineProperty, because this allows to exchange the XSS protection algorithms behind …
=> fix: allow configuring the XSS protection behavior

docs/timeline/index.html, types/index.d.ts
Fixes the reference for the filter options configuration to use the interface exported by js-xss directly, leaving the namespace out. This should then fix the typescript errors in #1015
=> fix: reference to IFilterXSSOptions

lib/timeline/component/item/Item.js
Symptom before fix: an item cannot be moved (item time update by drag and drop).
Error logged in browser console:
Uncaught TypeError: this.hammer is undefined
=> fix: wrong instance member name.

README.md
Add missing `https:` in the urls in the README's example. The current code doesn't work since the URLs don't resolve.
=> Fix urls in the readme example

types/index.d.ts
This pull request adds 'isCluster' to the TimelineEventPropertiesResult. It exists in JS, but doesn't have the typing in TS.   getEventProperties(event) in Timeline.js returns a boolean for 'isCluster'.
=> fix: Update TimelineEventPropertiesResult typing

lib/timeline/Stack.js
fixes #1233
Well this was a fun challenge. This PR improves the performance of the stack, substack, and stackSubgroups functions. It also refactors them so that they all use a single common function.
I tested this against a ~1,600 item dataset. Before the change, stacking took 4.6 seconds. After the change it takes 84 milliseconds.
I think the new algorithm is O(n log n) for the best case (order of items matches chronological order) and O(n^2) for the worst case (order of items is the exact inverse of chronological order). I believe the previous stacking algorithm was actually O(n^2 log n), and not the O(n^2) mentioned in yotamberk/timeline-plus#26. But I'm not a computer scientist, so someone else would have to confirm this.
I have tested this using the "subgroups" example and it appears …
=> feat: Improve performance of stack function

.circleci/config.yml, lib/util.js
The “private” _idProp has been removed and instead there idProp in the official supported API. I kept the older version there as a fallback just in case something actually depends on it.
=> fix(data): primarily use public API idProp

types/index.d.ts
The property `TimelineItem.content` can be of type `HTMLElement` as well as `string` (as demonstrated by the HTML sample). 
Note that the property `TimelineGroup.content` already is of this type `string | HTMLElement`.
=> TimelineItem.content can hold HTMLElement

lib/timeline/Core.js
This fixes #1640.  Not sure if there's a better approach, but it appears that if you initialize the timeline with a configured `moment`, and then after the fact set the orientation to `both`, the full options are never passed to the `TimeAxis`.
A minimal reproduction is available in the issue.
=> Fix second time axis not using configured moment when added after the fact

package-lock.json, package.json, rollup.config.js
We also use this one for the other builds so it's not a new dependency.
=> refactor(build): replace unmaintained rollup-plugin-css-porter by rollup-plugin-postcss

lib/bundle-legacy.js, lib/entry-esnext.js, lib/entry-standalone.js, lib/shared/Activator.js, lib/shared/Configurator.js, lib/shared/Popup.js, lib/timeline/Core.js, lib/timeline/component/CustomTime.js, lib/timeline/component/DataAxis.js, lib/timeline/component/ItemSet.js, lib/timeline/component/TimeAxis.js, lib/timeline/component/item/Item.js
Tests run in Node without CSS support. The style imports were ignored anyway. Not importing CSS into tests in the first place will make things easier, especially transition to ESM where require won't work.
=> refactor(styles): remove CSS from tests

lib/timeline/Timeline.js
Rolling mode keeps the current time centered. Using focus while rolling mode is engaged doesn't make any sense. If the user uses focus while rolling mode is engaged, it does make sense to automatically disengage rolling mode.
Fixes #573
=> fix(range): disable rolling mode on focus

lib/timeline/component/CustomTime.js
fixes #1739 
This PR resolves a ReferenceError that occurs when clicking on custom markers. The issue was introduced in #367, where all `marker` references were updated to use `this`. However, a classic `function(){}` expression was used for an event listener without proper `this` binding, leading to the error.
To fix this, I updated it (and other existing one) to use an arrow function. I think it is better than `.bind(this)` nowadays.
=> Fix ReferenceError when clicking custom markers
